-- Amazon Nova Integration Tables
-- Run this migration to add Nova-related tables to your database

-- Table: borrower_risk_scores
-- Stores risk assessment scores generated by Nova 2 Lite
CREATE TABLE IF NOT EXISTS borrower_risk_scores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  borrower_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  risk_score INT NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
  risk_band VARCHAR(20) NOT NULL CHECK (risk_band IN ('Low', 'Medium', 'High')),
  key_factors JSONB NOT NULL DEFAULT '[]',
  recommendation VARCHAR(20) NOT NULL CHECK (recommendation IN ('Approve', 'Decline', 'Conditional')),
  reasoning TEXT,
  nova_response JSONB,
  calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_borrower_risk_scores_borrower_id ON borrower_risk_scores(borrower_id);
CREATE INDEX IF NOT EXISTS idx_borrower_risk_scores_risk_band ON borrower_risk_scores(risk_band);

-- Table: disputes
-- Stores loan disputes with Nova-generated analysis
CREATE TABLE IF NOT EXISTS disputes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_id UUID NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
  borrower_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  evidence JSONB DEFAULT '{}',
  nova_summary TEXT,
  nova_suggestion VARCHAR(255),
  nova_confidence INT CHECK (nova_confidence >= 0 AND nova_confidence <= 100),
  nova_flags JSONB DEFAULT '[]',
  nova_response JSONB,
  status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewing', 'resolved', 'escalated')),
  resolution TEXT,
  resolved_by UUID REFERENCES users(id),
  resolved_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for disputes
CREATE INDEX IF NOT EXISTS idx_disputes_loan_id ON disputes(loan_id);
CREATE INDEX IF NOT EXISTS idx_disputes_borrower_id ON disputes(borrower_id);
CREATE INDEX IF NOT EXISTS idx_disputes_lender_id ON disputes(lender_id);
CREATE INDEX IF NOT EXISTS idx_disputes_status ON disputes(status);
CREATE INDEX IF NOT EXISTS idx_disputes_created_at ON disputes(created_at);

-- Table: loan_agreements (optional - for storing full agreement text)
-- Links to Nova's agreement analysis
CREATE TABLE IF NOT EXISTS loan_agreements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_id UUID NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
  agreement_text TEXT NOT NULL,
  clauses JSONB DEFAULT '[]',
  signatures JSONB DEFAULT '{}',
  is_valid BOOLEAN DEFAULT TRUE,
  missing_clauses JSONB DEFAULT '[]',
  risk_flags JSONB DEFAULT '[]',
  nova_analysis JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_loan_agreements_loan_id ON loan_agreements(loan_id);

-- Table: nova_api_logs (for monitoring Nova usage and costs)
CREATE TABLE IF NOT EXISTS nova_api_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  borrower_id UUID REFERENCES users(id),
  dispute_id UUID REFERENCES disputes(id),
  operation VARCHAR(50) NOT NULL, -- 'risk_scoring', 'dispute_analysis', 'agreement_analysis'
  prompt_tokens INT,
  response_tokens INT,
  latency_ms INT,
  success BOOLEAN DEFAULT TRUE,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_nova_api_logs_operation ON nova_api_logs(operation);
CREATE INDEX IF NOT EXISTS idx_nova_api_logs_created_at ON nova_api_logs(created_at);

-- View: borrower_loan_stats (for risk scoring input)
-- Calculates metrics needed for Nova risk assessment
CREATE OR REPLACE VIEW borrower_loan_stats AS
SELECT 
  u.id as borrower_id,
  u.full_name,
  u.phone_number,
  COUNT(DISTINCT l.id) as total_loans,
  SUM(CASE WHEN l.status = 'defaulted' THEN 1 ELSE 0 END)::float / 
    NULLIF(COUNT(l.id), 0) * 100 as default_rate,
  COALESCE(AVG(EXTRACT(DAY FROM l.repayment_start_date - l.created_at)), 30) as avg_repayment_days,
  COUNT(DISTINCT DATE_TRUNC('quarter', l.created_at)) as loan_frequency,
  COALESCE(COUNT(DISTINCT d.id), 0) as dispute_count
FROM users u
LEFT JOIN loans l ON u.id = l.borrower_id
LEFT JOIN disputes d ON u.id = d.borrower_id
GROUP BY u.id, u.full_name, u.phone_number;

-- View: dispute_queue (for admin dashboard)
CREATE OR REPLACE VIEW dispute_queue AS
SELECT 
  d.id,
  d.loan_id,
  u_borrower.full_name as borrower_name,
  u_lender.full_name as lender_name,
  l.principal_amount,
  d.reason,
  d.nova_summary,
  d.nova_suggestion,
  d.nova_confidence,
  d.status,
  d.created_at,
  EXTRACT(DAY FROM CURRENT_TIMESTAMP - d.created_at) as days_open
FROM disputes d
JOIN users u_borrower ON d.borrower_id = u_borrower.id
JOIN users u_lender ON d.lender_id = u_lender.id
JOIN loans l ON d.loan_id = l.id
ORDER BY d.created_at DESC;

-- End of migration
